import React, { createContext, useState, useContext, useEffect } from 'react';

// Расширенные переводы для сайта
const translations = {
    ru: {
        // Общие
        appointment: 'Запись на прием',
        consultation: 'Консультация',
        more: 'Подробнее',
        readMore: 'Читать далее',
        all: 'Все',
        back: 'Назад',
        next: 'Далее',
        submit: 'Отправить',
        cancel: 'Отмена',
        close: 'Закрыть',
        send: 'Отправить',
        search: 'Поиск',
        save: 'Сохранить',
        delete: 'Удалить',
        edit: 'Редактировать',
        add: 'Добавить',
        confirm: 'Подтвердить',
        yes: 'Да',
        no: 'Нет',
        loading: 'Загрузка...',

        loginTitle: 'Войдите в личный кабинет',
        registerTitle: 'Создайте аккаунт',
        fullNamePlaceholder: 'Иванов Иван Иванович',
        password: 'Пароль',
        loginError: 'Ошибка при входе',
        connectionError: 'Ошибка соединения с сервером',
        privacyRequired: 'Необходимо согласиться на обработку персональных данных',
        privacyAgreement: 'Я согласен на',
        privacyPolicy: 'обработку персональных данных',
        userAgreement: 'пользовательского соглашения',
        and: 'и',
        register: 'Зарегистрироваться',
        noAccount: 'Нет аккаунта? Зарегистрироваться',
        hasAccount: 'Уже есть аккаунт? Войти',
        privacyPolicyText: 'Политика обработки персональных данных\n\nНажимая кнопку "Зарегистрироваться", вы даете согласие на обработку своих персональных данных в соответствии с Федеральным законом №152-ФЗ "О персональных данных" и политикой конфиденциальности Клиники Паллуа.',
        userAgreementText: 'Пользовательское соглашение\n\nРегистрируясь на сайте, вы соглашаетесь с правилами использования сервиса и обязуетесь предоставлять достоверную информацию о себе.',
        
        // Меню
        home: 'Главная',
        about: 'О клинике',
        services: 'Услуги',
        specialists: 'Специалисты',
        prices: 'Цены',
        reviews: 'Отзывы',
        contacts: 'Контакты',
        appointmentMenu: 'Записаться',
        
        // Шапка
        address: 'Адрес',
        callback: 'Обратный звонок',
        toggleTheme: 'Переключить тему',
        toDark: 'на темную',
        toLight: 'на светлую',
        openMenu: 'Открыть меню',
        login: 'Войти',
        logout: 'Выйти',
        dashboard: 'Личный кабинет',
        adminPanel: 'Админ-панель',
        myAppointments: 'Мои записи',
        accessibilityVersion: 'Версия для слабовидящих',
        accessibilityOn: 'Режим для слабовидящих включен',
        accessibilityOff: 'Режим для слабовидящих выключен',
        
        // Hero
        heroTitle: 'Клиника Паллуа',
        heroSubtitle: 'Профессор, Доктор Мед. Н. Паллуа ФЕБОПРАС',
        heroDescription: 'На протяжении десятилетий пластическая, реконструктивная и эстетическая хирургия на самом высоком международном уровне.',
        bookAppointment: 'Записаться на прием',
        callUs: 'Позвонить нам',
        expertDoctors: 'Врачей экспертов',
        yearsOfWork: 'Лет работы',
        happyPatients: 'Довольных пациентов',
        qualityMark: 'Наш знак качества',
        
        // About
        ourStrengths: 'Наши сильные стороны',
        aboutDescription: 'Благодаря нашему многолетнему опыту и проверенной специализации, наши сильные стороны находятся там, где другие достигают предела своих возможностей:',
        amongOther: 'Среди прочего:',
        complexProcedures: 'Сложные процедуры в области лица и шеи',
        correctiveSurgeries: 'Корректирующие операции после неудачных процедур',
        removalImplants: 'Удаление имплантированных инородных материалов',
        modernEquipment: 'Современное оборудование',
        equipmentDesc: 'Используем только новейшее оборудование',
        experiencedSpecialists: 'Опытные специалисты',
        specialistsDesc: 'Врачи с многолетним стажем и регулярным повышением квалификации',
        individualApproach: 'Индивидуальный подход',
        approachDesc: 'Для каждого пациента разрабатывается персональная программа',
        comfortableConditions: 'Комфортные условия',
        conditionsDesc: 'Уютные кабинеты и заботливый персонал для вашего удобства',
        ourHistory: 'Наша история',
        foundation: 'Основание клиники',
        certification: 'Сертификации',
        newTechnologies: 'Внедрение новых технологий',
        newClinics: 'Открытие новых клиник',
        happyPatients10k: '10 000+ довольных пациентов',
        yearsSuccessful: 'Лет успешной работы',
        doctorsSpecialists: 'Врачей-специалистов',
        publications: 'Публикаций',
        satisfiedPatients: 'Довольных пациентов',
        
        // Specialists
        ourSpecialists: 'Наши специалисты',
        specialistsDescription: 'Высококвалифицированные врачи с многолетним опытом работы. Постоянно повышают квалификацию и следят за новейшими разработками в медицине',
        experience: 'Опыт',
        specialization: 'Специализация',
        details: 'Подробнее',
        specialistsCount: 'Специалистов',
        directions: 'Направлений',
        qualification: 'Квалификация',
        consultations: 'Консультации',
        
        // WhyUs
        whyChooseUs: 'Почему выбирают Клинику Паллуа',
        whyDescription: 'На протяжении десятилетий мы сочетаем безупречную хирургическую технику, международный опыт и индивидуальный подход к каждому пациенту',
        internationalLevel: 'Международный уровень',
        internationalDesc: 'Работа по европейским стандартам ФЕБОПРАС',
        yearsExperience: '30+ лет опыта',
        experienceDesc: 'Профессор Паллуа - основатель клиники с 1990-х годов',
        individualApproachTitle: 'Индивидуальный подход',
        individualDesc: 'Каждая операция тщательно планируется под конкретного пациента',
        modernTech: 'Современные технологии',
        techDesc: 'Используем передовое оборудование и методики',
        naturalResults: 'Естественные результаты',
        naturalDesc: 'Сохранение индивидуальности и гармонии черт',
        complexApproach: 'Комплексный подход',
        complexDesc: 'От консультации до полной реабилитации',
        safetyQuality: 'Безопасность и качество',
        safetyDesc: 'Сертификация ФЕБОПРАС гарантирует европейские стандарты безопасности всех процедур',
        confidentiality: 'Конфиденциальность',
        confidentialityDesc: 'Полная анонимность и конфиденциальность лечения. Мы ценим ваше доверие',
        expertRating: 'Экспертная оценка',
        expertDesc: 'Более 10 000 довольных пациентов и сотни коллег по всему миру рекомендуют нас',
        yearsProfExperience: 'лет опыта профессора Паллуа',
        successfulSurgeries: 'успешных операций',
        countriesPatients: 'стран, откуда к нам приезжают пациенты',
        recommendFriends: 'пациентов рекомендуют нас друзьям',
        
        // Reviews
        patientReviews: 'Отзывы пациентов',
        reviewsDescription: 'Что говорят наши пациенты о лечении в клинике. Мы ценим каждое мнение и постоянно работаем над улучшением качества услуг',
        leaveReview: 'Оставить отзыв',
        yourOpinion: 'Ваше мнение помогает нам становиться лучше',
        useful: 'Полезно',
        reply: 'Ответить',
        share: 'Поделиться',
        
        // Testimonials
        testimonials: 'Рекомендации',
        testimonialsDescription: 'Наши пациенты делятся своими историями выздоровления',
        patientsRecommend: 'Пациентов рекомендуют нас',
        averageRating: 'Средняя оценка клиники',
        positiveReviews: 'Положительных отзывов',
        
        // DiseasesMethods
        ourServices: 'Наши услуги',
        men: 'Мужчины',
        women: 'Женщины',
        diagnosticsAppointment: 'Запись на диагностику',
        diagnosticsDesc: 'Запишитесь на комплексное обследование со скидкой 15%',
        secondOpinion: 'Второе мнение',
        secondOpinionDesc: 'Получите консультацию нескольких специалистов',
        learnMore: 'Узнать больше',
        
        // Articles
        usefulArticles: 'Полезные статьи',
        articlesDescription: 'Актуальная информация',
        readArticle: 'Читать статью',
        
        // Contact
        contactsTitle: 'Контакты',
        contactDescription: 'Свяжитесь с нами любым удобным способом',
        addressTitle: 'Адрес',
        phones: 'Телефоны',
        callsAccepted: 'Звонки принимаются ежедневно с 8:00 до 20:00',
        email: 'Email',
        replyWithin: 'Отвечаем в течение 24 часов',
        workingHours: 'График работы',
        monFri: 'Пн-Пт',
        satSun: 'Сб-Вс',
        appointmentRequired: 'Прием по предварительной записи',
        socialMedia: 'Мы в социальных сетях',
        writeUs: 'Напишите нам',
        formSubtitle: 'Заполните форму и мы свяжемся с вами в ближайшее время',
        yourName: 'Ваше имя',
        phone: 'Телефон',
        emailOptional: 'Email (необязательно)',
        subject: 'Тема обращения',
        yourMessage: 'Ваше сообщение',
        sendMessage: 'Отправить сообщение',
        viewOnMap: 'Посмотреть на карте',
        
        // Footer
        menu: 'Меню',
        aboutClinic: 'О клинике',
        appointmentOnline: 'Записаться онлайн',
        viewPrices: 'Посмотреть цены',
        allRightsReserved: 'Все права защищены',
        privacyPolicy: 'Политика конфиденциальности',
        offerAgreement: 'Договор оферты',
        licenses: 'Лицензии',
        careSince: 'Забота о вашем здоровье с 2010 года',
        
        // Modals
        bookConsultation: 'Запись на консультацию',
        contactDetails: 'Контактные данные',
        fullName: 'ФИО',
        selectDoctor: 'Выберите врача',
        selectService: 'Выберите услугу',
        selectDate: 'Выберите дату',
        selectTime: 'Выберите время',
        comment: 'Комментарий',
        confirmAppointment: 'Подтверждение записи',
        yourData: 'Ваши данные',
        appointmentDetails: 'Детали записи',
        doctor: 'Врач',
        service: 'Услуга',
        dateTime: 'Дата и время',
        agreePrivacy: 'Я согласен на обработку персональных данных',
        confirmInfo: 'и подтверждаю корректность указанной информации',
        
        // Statuses
        pending: 'Ожидает',
        confirmed: 'Подтверждена',
        cancelled: 'Отменена',
        completed: 'Завершена',
        active: 'Активен',
        inactive: 'Неактивен',
        
        // Admin
        adminPanelTitle: 'Админ-панель',
        clinicManagement: 'Управление клиникой',
        totalAppointments: 'Всего записей',
        pendingAppointments: 'Ожидают',
        confirmedAppointments: 'Подтверждены',
        completedAppointments: 'Завершены',
        cancelledAppointments: 'Отменены',
        filters: 'Фильтры',
        allStatuses: 'Все статусы',
        allDoctors: 'Все врачи',
        dateFrom: 'Дата от',
        dateTo: 'Дата до',
        reset: 'Сбросить',
        date: 'Дата',
        time: 'Время',
        patient: 'Пациент',
        status: 'Статус',
        actions: 'Действия',
        addDoctor: 'Добавить врача',
        addService: 'Добавить услугу',
        scheduleSettings: 'Настройка расписания врачей',
        selectDoctorFirst: 'Выберите врача',
        workingDay: 'Рабочий день',
        exceptions: 'Исключения (отпуск, больничный)',
        vacation: 'Отпуск',
        sickLeave: 'Больничный',
        other: 'Другое',
        addException: 'Добавить',
        saveSchedule: 'Сохранить расписание',
        noAppointments: 'Нет записей',
        editDoctor: 'Редактировать врача',
        deleteDoctor: 'Удалить врача',
        deleteConfirm: 'Вы уверены?',
        category: 'Категория',
        price: 'Цена',
        duration: 'Длительность',
        
        // Dashboard
        personalAccount: 'Личный кабинет',
        myAppointmentsTitle: 'Мои записи',
        noAppointmentsYet: 'У вас пока нет записей',
        cancelAppointment: 'Отменить запись',
        cancelConfirm: 'Вы уверены, что хотите отменить запись?',
        loginRequired: 'Войдите в личный кабинет',
        loginToView: 'Для просмотра записей необходимо авторизоваться',
    },
    
    en: {
        // General
        appointment: 'Make an Appointment',
        consultation: 'Consultation',
        more: 'More',
        readMore: 'Read More',
        all: 'All',
        back: 'Back',
        next: 'Next',
        submit: 'Submit',
        cancel: 'Cancel',
        close: 'Close',
        send: 'Send',
        search: 'Search',
        save: 'Save',
        delete: 'Delete',
        edit: 'Edit',
        add: 'Add',
        confirm: 'Confirm',
        yes: 'Yes',
        no: 'No',
        loading: 'Loading...',

        loginTitle: 'Login to your account',
        registerTitle: 'Create an account',
        fullNamePlaceholder: 'John Doe',
        password: 'Password',
        loginError: 'Login error',
        connectionError: 'Connection error',
        privacyRequired: 'You must agree to the processing of personal data',
        privacyAgreement: 'I agree to',
        privacyPolicy: 'privacy policy',
        userAgreement: 'user agreement',
        and: 'and',
        register: 'Register',
        noAccount: 'No account? Register',
        hasAccount: 'Already have an account? Login',
        privacyPolicyText: 'Privacy Policy\n\nBy clicking "Register", you consent to the processing of your personal data in accordance with Federal Law No. 152-FZ "On Personal Data" and the privacy policy of Pallua Clinic.',
        userAgreementText: 'User Agreement\n\nBy registering on the site, you agree to the terms of service and undertake to provide accurate information about yourself.',
        
        // Menu
        home: 'Home',
        about: 'About Clinic',
        services: 'Services',
        specialists: 'Specialists',
        prices: 'Prices',
        reviews: 'Reviews',
        contacts: 'Contacts',
        appointmentMenu: 'Book Appointment',
        
        // Header
        address: 'Address',
        callback: 'Callback',
        toggleTheme: 'Toggle theme',
        toDark: 'to dark',
        toLight: 'to light',
        openMenu: 'Open menu',
        login: 'Login',
        logout: 'Logout',
        dashboard: 'Dashboard',
        adminPanel: 'Admin Panel',
        myAppointments: 'My Appointments',
        accessibilityVersion: 'Accessibility version',
        accessibilityOn: 'Accessibility mode enabled',
        accessibilityOff: 'Accessibility mode disabled',
        
        // Hero
        heroTitle: 'Pallua Clinic',
        heroSubtitle: 'Professor, Dr. Med. N. Pallua FEBOPRAS',
        heroDescription: 'For decades, plastic, reconstructive and aesthetic surgery at the highest international level.',
        bookAppointment: 'Book Appointment',
        callUs: 'Call Us',
        expertDoctors: 'Expert Doctors',
        yearsOfWork: 'Years of Work',
        happyPatients: 'Happy Patients',
        qualityMark: 'Quality Mark',
        
        // About
        ourStrengths: 'Our Strengths',
        aboutDescription: 'Thanks to our many years of experience and proven specialization, our strengths lie where others reach their limits:',
        amongOther: 'Among other things:',
        complexProcedures: 'Complex procedures in the face and neck area',
        correctiveSurgeries: 'Corrective surgeries after failed procedures',
        removalImplants: 'Removal of implanted foreign materials causing disfigurement',
        modernEquipment: 'Modern Equipment',
        equipmentDesc: 'We use only the latest equipment',
        experiencedSpecialists: 'Experienced Specialists',
        specialistsDesc: 'Doctors with many years of experience and regular advanced training',
        individualApproach: 'Individual Approach',
        approachDesc: 'A personal program is developed for each patient',
        comfortableConditions: 'Comfortable Conditions',
        conditionsDesc: 'Cozy rooms and caring staff for your comfort',
        ourHistory: 'Our History',
        foundation: 'Foundation of the clinic',
        certification: 'Certifications',
        newTechnologies: 'Implementation of new technologies',
        newClinics: 'Opening of new clinics',
        happyPatients10k: '10,000+ satisfied patients',
        yearsSuccessful: 'Years of successful work',
        doctorsSpecialists: 'Specialist doctors',
        publications: 'Publications',
        satisfiedPatients: 'Satisfied patients',
        
        // Specialists
        ourSpecialists: 'Our Specialists',
        specialistsDescription: 'Highly qualified doctors with many years of experience. Constantly improving their skills and keeping up with the latest developments in medicine',
        experience: 'Experience',
        specialization: 'Specialization',
        details: 'Details',
        specialistsCount: 'Specialists',
        directions: 'Directions',
        qualification: 'Qualification',
        consultations: 'Consultations',
        
        // WhyUs
        whyChooseUs: 'Why Choose Pallua Clinic',
        whyDescription: 'For decades, we have combined impeccable surgical technique, international experience and an individual approach to each patient',
        internationalLevel: 'International Level',
        internationalDesc: 'Working according to European FEBOPRAS standards',
        yearsExperience: '30+ Years of Experience',
        experienceDesc: 'Professor Pallua - founder of the clinic since the 1990s',
        individualApproachTitle: 'Individual Approach',
        individualDesc: 'Each operation is carefully planned for the specific patient',
        modernTech: 'Modern Technologies',
        techDesc: 'We use advanced equipment and techniques',
        naturalResults: 'Natural Results',
        naturalDesc: 'Preservation of individuality and harmony of features',
        complexApproach: 'Comprehensive Approach',
        complexDesc: 'From consultation to full rehabilitation',
        safetyQuality: 'Safety and Quality',
        safetyDesc: 'FEBOPRAS certification guarantees European safety standards for all procedures',
        confidentiality: 'Confidentiality',
        confidentialityDesc: 'Complete anonymity and confidentiality of treatment. We value your trust',
        expertRating: 'Expert Rating',
        expertDesc: 'Over 10,000 satisfied patients and hundreds of colleagues worldwide recommend us',
        yearsProfExperience: 'years of Professor Pallua\'s experience',
        successfulSurgeries: 'successful surgeries',
        countriesPatients: 'countries from which patients come to us',
        recommendFriends: 'of patients recommend us to friends',
        
        // Reviews
        patientReviews: 'Patient Reviews',
        reviewsDescription: 'What our patients say about treatment at the clinic. We value every opinion and constantly work to improve the quality of services',
        leaveReview: 'Leave a Review',
        yourOpinion: 'Your opinion helps us become better',
        useful: 'Useful',
        reply: 'Reply',
        share: 'Share',
        
        // Testimonials
        testimonials: 'Testimonials',
        testimonialsDescription: 'Our patients share their recovery stories',
        patientsRecommend: 'Patients recommend us',
        averageRating: 'Average clinic rating',
        positiveReviews: 'Positive reviews',
        
        // DiseasesMethods
        ourServices: 'Our Services',
        men: 'Men',
        women: 'Women',
        diagnosticsAppointment: 'Diagnostics Appointment',
        diagnosticsDesc: 'Book a comprehensive examination with a 15% discount',
        secondOpinion: 'Second Opinion',
        secondOpinionDesc: 'Get a consultation from several specialists',
        learnMore: 'Learn More',
        
        // Articles
        usefulArticles: 'Useful Articles',
        articlesDescription: 'Current Information',
        readArticle: 'Read Article',
        
        // Contact
        contactsTitle: 'Contacts',
        contactDescription: 'Contact us in any convenient way',
        addressTitle: 'Address',
        phones: 'Phones',
        callsAccepted: 'Calls are accepted daily from 8:00 to 20:00',
        email: 'Email',
        replyWithin: 'We reply within 24 hours',
        workingHours: 'Working Hours',
        monFri: 'Mon-Fri',
        satSun: 'Sat-Sun',
        appointmentRequired: 'Appointment required',
        socialMedia: 'We are on social media',
        writeUs: 'Write to us',
        formSubtitle: 'Fill out the form and we will contact you shortly',
        yourName: 'Your Name',
        phone: 'Phone',
        emailOptional: 'Email (optional)',
        subject: 'Subject',
        yourMessage: 'Your Message',
        sendMessage: 'Send Message',
        viewOnMap: 'View on Map',
        
        // Footer
        menu: 'Menu',
        aboutClinic: 'About Clinic',
        appointmentOnline: 'Book Online',
        viewPrices: 'View Prices',
        allRightsReserved: 'All Rights Reserved',
        privacyPolicy: 'Privacy Policy',
        offerAgreement: 'Offer Agreement',
        licenses: 'Licenses',
        careSince: 'Taking care of your health since 2010',
        
        // Modals
        bookConsultation: 'Book a Consultation',
        contactDetails: 'Contact Details',
        fullName: 'Full Name',
        selectDoctor: 'Select Doctor',
        selectService: 'Select Service',
        selectDate: 'Select Date',
        selectTime: 'Select Time',
        comment: 'Comment',
        confirmAppointment: 'Confirm Appointment',
        yourData: 'Your Data',
        appointmentDetails: 'Appointment Details',
        doctor: 'Doctor',
        service: 'Service',
        dateTime: 'Date and Time',
        agreePrivacy: 'I agree to the processing of personal data',
        confirmInfo: 'and confirm the correctness of the information',
        
        // Statuses
        pending: 'Pending',
        confirmed: 'Confirmed',
        cancelled: 'Cancelled',
        completed: 'Completed',
        active: 'Active',
        inactive: 'Inactive',
        
        // Admin
        adminPanelTitle: 'Admin Panel',
        clinicManagement: 'Clinic Management',
        totalAppointments: 'Total Appointments',
        pendingAppointments: 'Pending',
        confirmedAppointments: 'Confirmed',
        completedAppointments: 'Completed',
        cancelledAppointments: 'Cancelled',
        filters: 'Filters',
        allStatuses: 'All Statuses',
        allDoctors: 'All Doctors',
        dateFrom: 'Date From',
        dateTo: 'Date To',
        reset: 'Reset',
        date: 'Date',
        time: 'Time',
        patient: 'Patient',
        status: 'Status',
        actions: 'Actions',
        addDoctor: 'Add Doctor',
        addService: 'Add Service',
        scheduleSettings: 'Doctor Schedule Settings',
        selectDoctorFirst: 'Select a doctor',
        workingDay: 'Working Day',
        exceptions: 'Exceptions (vacation, sick leave)',
        vacation: 'Vacation',
        sickLeave: 'Sick Leave',
        other: 'Other',
        addException: 'Add',
        saveSchedule: 'Save Schedule',
        noAppointments: 'No Appointments',
        editDoctor: 'Edit Doctor',
        deleteDoctor: 'Delete Doctor',
        deleteConfirm: 'Are you sure?',
        category: 'Category',
        price: 'Price',
        duration: 'Duration',
        
        // Dashboard
        personalAccount: 'Personal Account',
        myAppointmentsTitle: 'My Appointments',
        noAppointmentsYet: 'You have no appointments yet',
        cancelAppointment: 'Cancel Appointment',
        cancelConfirm: 'Are you sure you want to cancel the appointment?',
        loginRequired: 'Login to your account',
        loginToView: 'Authorization required to view appointments',
    },
    
    de: {
        // General
        appointment: 'Termin vereinbaren',
        consultation: 'Beratung',
        more: 'Mehr',
        readMore: 'Weiterlesen',
        all: 'Alle',
        back: 'Zurück',
        next: 'Weiter',
        submit: 'Absenden',
        cancel: 'Abbrechen',
        close: 'Schließen',
        send: 'Senden',
        search: 'Suchen',
        save: 'Speichern',
        delete: 'Löschen',
        edit: 'Bearbeiten',
        add: 'Hinzufügen',
        confirm: 'Bestätigen',
        yes: 'Ja',
        no: 'Nein',
        loading: 'Laden...',

        loginTitle: 'Melden Sie sich an',
        registerTitle: 'Erstellen Sie ein Konto',
        fullNamePlaceholder: 'Max Mustermann',
        password: 'Passwort',
        loginError: 'Anmeldefehler',
        connectionError: 'Verbindungsfehler',
        privacyRequired: 'Sie müssen der Datenverarbeitung zustimmen',
        privacyAgreement: 'Ich stimme zu',
        privacyPolicy: 'Datenschutzerklärung',
        userAgreement: 'Nutzungsbedingungen',
        and: 'und',
        register: 'Registrieren',
        noAccount: 'Kein Konto? Registrieren',
        hasAccount: 'Haben Sie bereits ein Konto? Anmelden',
        privacyPolicyText: 'Datenschutzerklärung\n\nMit dem Klicken auf "Registrieren" willigen Sie in die Verarbeitung Ihrer personenbezogenen Daten gemäß Bundesgesetz Nr. 152-FZ "Über personenbezogene Daten" und der Datenschutzerklärung der Pallua Klinik ein.',
        userAgreementText: 'Nutzungsbedingungen\n\nMit der Registrierung auf der Website stimmen Sie den Nutzungsbedingungen zu und verpflichten sich, wahrheitsgemäße Angaben zu Ihrer Person zu machen.',
        
        // Menu
        home: 'Startseite',
        about: 'Über die Klinik',
        services: 'Dienstleistungen',
        specialists: 'Spezialisten',
        prices: 'Preise',
        reviews: 'Bewertungen',
        contacts: 'Kontakte',
        appointmentMenu: 'Termin vereinbaren',
        
        // Header
        address: 'Adresse',
        callback: 'Rückruf',
        toggleTheme: 'Thema wechseln',
        toDark: 'zu dunkel',
        toLight: 'zu hell',
        openMenu: 'Menü öffnen',
        login: 'Anmelden',
        logout: 'Abmelden',
        dashboard: 'Dashboard',
        adminPanel: 'Admin-Panel',
        myAppointments: 'Meine Termine',
        accessibilityVersion: 'Version für Sehbehinderte',
        accessibilityOn: 'Barrierefreiheitsmodus aktiviert',
        accessibilityOff: 'Barrierefreiheitsmodus deaktiviert',
        
        // Hero
        heroTitle: 'Pallua Klinik',
        heroSubtitle: 'Professor, Dr. Med. N. Pallua FEBOPRAS',
        heroDescription: 'Seit Jahrzehnten plastische, rekonstruktive und ästhetische Chirurgie auf höchstem internationalen Niveau.',
        bookAppointment: 'Termin vereinbaren',
        callUs: 'Rufen Sie uns an',
        expertDoctors: 'Fachärzte',
        yearsOfWork: 'Jahre Erfahrung',
        happyPatients: 'Zufriedene Patienten',
        qualityMark: 'Qualitätssiegel',
        
        // About
        ourStrengths: 'Unsere Stärken',
        aboutDescription: 'Dank unserer langjährigen Erfahrung und bewährten Spezialisierung liegen unsere Stärken dort, wo andere an ihre Grenzen stoßen:',
        amongOther: 'Unter anderem:',
        complexProcedures: 'Komplexe Eingriffe im Gesichts- und Halsbereich',
        correctiveSurgeries: 'Korrekturoperationen nach fehlgeschlagenen Eingriffen',
        removalImplants: 'Entfernung von implantierten Fremdmaterialien',
        modernEquipment: 'Moderne Ausstattung',
        equipmentDesc: 'Wir verwenden nur die neueste Ausstattung',
        experiencedSpecialists: 'Erfahrene Spezialisten',
        specialistsDesc: 'Ärzte mit langjähriger Erfahrung und regelmäßiger Weiterbildung',
        individualApproach: 'Individuelle Betreuung',
        approachDesc: 'Für jeden Patienten wird ein persönliches Programm erstellt',
        comfortableConditions: 'Komfortable Bedingungen',
        conditionsDesc: 'Gemütliche Räume und fürsorgliches Personal für Ihren Komfort',
        ourHistory: 'Unsere Geschichte',
        foundation: 'Gründung der Klinik',
        certification: 'Zertifizierungen',
        newTechnologies: 'Einführung neuer Technologien',
        newClinics: 'Eröffnung neuer Kliniken',
        happyPatients10k: '10.000+ zufriedene Patienten',
        yearsSuccessful: 'Jahre erfolgreiche Arbeit',
        doctorsSpecialists: 'Fachärzte',
        publications: 'Publikationen',
        satisfiedPatients: 'Zufriedene Patienten',
        
        // Specialists
        ourSpecialists: 'Unsere Spezialisten',
        specialistsDescription: 'Hochqualifizierte Ärzte mit langjähriger Erfahrung. Ständige Weiterbildung und neueste Entwicklungen in der Medizin',
        experience: 'Erfahrung',
        specialization: 'Spezialisierung',
        details: 'Details',
        specialistsCount: 'Spezialisten',
        directions: 'Fachrichtungen',
        qualification: 'Qualifikation',
        consultations: 'Beratungen',
        
        // WhyUs
        whyChooseUs: 'Warum die Pallua Klinik wählen',
        whyDescription: 'Seit Jahrzehnten verbinden wir tadellose Operationstechnik, internationale Erfahrung und individuelle Betreuung',
        internationalLevel: 'Internationales Niveau',
        internationalDesc: 'Arbeit nach europäischen FEBOPRAS-Standards',
        yearsExperience: '30+ Jahre Erfahrung',
        experienceDesc: 'Professor Pallua - Gründer der Klinik seit den 1990er Jahren',
        individualApproachTitle: 'Individuelle Betreuung',
        individualDesc: 'Jede Operation wird sorgfältig für den Patienten geplant',
        modernTech: 'Moderne Technologien',
        techDesc: 'Wir verwenden modernste Geräte und Techniken',
        naturalResults: 'Natürliche Ergebnisse',
        naturalDesc: 'Erhaltung der Individualität und Harmonie der Gesichtszüge',
        complexApproach: 'Umfassender Ansatz',
        complexDesc: 'Von der Beratung bis zur vollständigen Rehabilitation',
        safetyQuality: 'Sicherheit und Qualität',
        safetyDesc: 'FEBOPRAS-Zertifizierung garantiert europäische Sicherheitsstandards',
        confidentiality: 'Vertraulichkeit',
        confidentialityDesc: 'Vollständige Anonymität und Vertraulichkeit der Behandlung',
        expertRating: 'Expertenbewertung',
        expertDesc: 'Über 10.000 zufriedene Patienten und Hunderte von Kollegen weltweit empfehlen uns',
        yearsProfExperience: 'Jahre Erfahrung von Professor Pallua',
        successfulSurgeries: 'erfolgreiche Operationen',
        countriesPatients: 'Länder, aus denen Patienten zu uns kommen',
        recommendFriends: 'der Patienten empfehlen uns weiter',
        
        // Reviews
        patientReviews: 'Patientenbewertungen',
        reviewsDescription: 'Was unsere Patienten über die Behandlung in der Klinik sagen',
        leaveReview: 'Bewertung hinterlassen',
        yourOpinion: 'Ihre Meinung hilft uns, besser zu werden',
        useful: 'Nützlich',
        reply: 'Antworten',
        share: 'Teilen',
        
        // Testimonials
        testimonials: 'Empfehlungen',
        testimonialsDescription: 'Unsere Patienten teilen ihre Genesungsgeschichten',
        patientsRecommend: 'Patienten empfehlen uns',
        averageRating: 'Durchschnittliche Bewertung',
        positiveReviews: 'Positive Bewertungen',
        
        // DiseasesMethods
        ourServices: 'Unsere Leistungen',
        men: 'Männer',
        women: 'Frauen',
        diagnosticsAppointment: 'Termin zur Diagnostik',
        diagnosticsDesc: 'Vereinbaren Sie eine umfassende Untersuchung mit 15% Rabatt',
        secondOpinion: 'Zweitmeinung',
        secondOpinionDesc: 'Holen Sie sich eine Beratung von mehreren Spezialisten',
        learnMore: 'Mehr erfahren',
        
        // Articles
        usefulArticles: 'Nützliche Artikel',
        articlesDescription: 'Aktuelle Informationen',
        readArticle: 'Artikel lesen',
        
        // Contact
        contactsTitle: 'Kontakte',
        contactDescription: 'Kontaktieren Sie uns auf beliebigem Wege',
        addressTitle: 'Adresse',
        phones: 'Telefone',
        callsAccepted: 'Anrufe werden täglich von 8:00 bis 20:00 Uhr entgegengenommen',
        email: 'E-Mail',
        replyWithin: 'Wir antworten innerhalb von 24 Stunden',
        workingHours: 'Öffnungszeiten',
        monFri: 'Mo-Fr',
        satSun: 'Sa-So',
        appointmentRequired: 'Termin nach Vereinbarung',
        socialMedia: 'Wir in sozialen Medien',
        writeUs: 'Schreiben Sie uns',
        formSubtitle: 'Füllen Sie das Formular aus und wir werden uns in Kürze bei Ihnen melden',
        yourName: 'Ihr Name',
        phone: 'Telefon',
        emailOptional: 'E-Mail (optional)',
        subject: 'Betreff',
        yourMessage: 'Ihre Nachricht',
        sendMessage: 'Nachricht senden',
        viewOnMap: 'Auf Karte anzeigen',
        
        // Footer
        menu: 'Menü',
        aboutClinic: 'Über die Klinik',
        appointmentOnline: 'Online buchen',
        viewPrices: 'Preise anzeigen',
        allRightsReserved: 'Alle Rechte vorbehalten',
        privacyPolicy: 'Datenschutzerklärung',
        offerAgreement: 'Angebotsvereinbarung',
        licenses: 'Lizenzen',
        careSince: 'Sorge für Ihre Gesundheit seit 2010',
        
        // Modals
        bookConsultation: 'Beratung buchen',
        contactDetails: 'Kontaktdaten',
        fullName: 'Vollständiger Name',
        selectDoctor: 'Arzt auswählen',
        selectService: 'Leistung auswählen',
        selectDate: 'Datum auswählen',
        selectTime: 'Zeit auswählen',
        comment: 'Kommentar',
        confirmAppointment: 'Termin bestätigen',
        yourData: 'Ihre Daten',
        appointmentDetails: 'Termindetails',
        doctor: 'Arzt',
        service: 'Leistung',
        dateTime: 'Datum und Uhrzeit',
        agreePrivacy: 'Ich stimme der Verarbeitung personenbezogener Daten zu',
        confirmInfo: 'und bestätige die Richtigkeit der Angaben',
        
        // Statuses
        pending: 'Ausstehend',
        confirmed: 'Bestätigt',
        cancelled: 'Storniert',
        completed: 'Abgeschlossen',
        active: 'Aktiv',
        inactive: 'Inaktiv',
        
        // Admin
        adminPanelTitle: 'Admin-Panel',
        clinicManagement: 'Klinikverwaltung',
        totalAppointments: 'Alle Termine',
        pendingAppointments: 'Ausstehend',
        confirmedAppointments: 'Bestätigt',
        completedAppointments: 'Abgeschlossen',
        cancelledAppointments: 'Storniert',
        filters: 'Filter',
        allStatuses: 'Alle Status',
        allDoctors: 'Alle Ärzte',
        dateFrom: 'Datum von',
        dateTo: 'Datum bis',
        reset: 'Zurücksetzen',
        date: 'Datum',
        time: 'Zeit',
        patient: 'Patient',
        status: 'Status',
        actions: 'Aktionen',
        addDoctor: 'Arzt hinzufügen',
        addService: 'Leistung hinzufügen',
        scheduleSettings: 'Arztplan-Einstellungen',
        selectDoctorFirst: 'Arzt auswählen',
        workingDay: 'Arbeitstag',
        exceptions: 'Ausnahmen (Urlaub, Krankheit)',
        vacation: 'Urlaub',
        sickLeave: 'Krankheit',
        other: 'Andere',
        addException: 'Hinzufügen',
        saveSchedule: 'Plan speichern',
        noAppointments: 'Keine Termine',
        editDoctor: 'Arzt bearbeiten',
        deleteDoctor: 'Arzt löschen',
        deleteConfirm: 'Sind Sie sicher?',
        category: 'Kategorie',
        price: 'Preis',
        duration: 'Dauer',
        
        // Dashboard
        personalAccount: 'Persönlicher Bereich',
        myAppointmentsTitle: 'Meine Termine',
        noAppointmentsYet: 'Sie haben noch keine Termine',
        cancelAppointment: 'Termin stornieren',
        cancelConfirm: 'Möchten Sie den Termin wirklich stornieren?',
        loginRequired: 'Melden Sie sich an',
        loginToView: 'Zum Anzeigen der Termine ist eine Anmeldung erforderlich',
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('ru');
    
    useEffect(() => {
        const savedLanguage = localStorage.getItem('language');
        if (savedLanguage && translations[savedLanguage]) {
            setLanguage(savedLanguage);
        }
    }, []);
    
    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.lang = language;
    }, [language]);
    
    const t = (key) => {
        return translations[language]?.[key] || key;
    };
    
    const changeLanguage = (lang) => {
        if (translations[lang]) {
            setLanguage(lang);
        }
    };
    
    return (
        <LanguageContext.Provider value={{ language, t, changeLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
};